posthog_analytics_enabled:
  type: bool
  default: false
  description: "Enable PostHog analytics tracking"

posthog_key:
  type: string
  default: ""
  description: "PostHog Project API Key"

posthog_host:
  type: string
  default: "https://us.i.posthog.com"
  description: "PostHog Host URL"

track_pageviews:
  type: bool
  default: true
  description: "Track page views"

track_user_actions:
  type: bool
  default: true
  description: "Track user actions (clicks, etc.)"

track_search:
  type: bool
  default: true
  description: "Track search queries"

autocapture:
  type: bool
  default: true
  description: "Enable PostHog autocapture"
